name: Test that action works

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: skaugvoll-actions/devlake-health-check@v1.0.1-beta
        with:
          url: http://google.com # should always be up
          repository: su-sisk/devlake-test-repo
          serviceName: saes
          labels: saes,dora,incident,down
        env:
          gh_token: ${{ secrets.GH_PAT }}
      - uses: skaugvoll-actions/devlake-health-check@v1.0.1-beta
        with:
          url: http://googlee.com # should return >400, create issue
          repository: su-sisk/devlake-test-repo
          serviceName: saes
          labels: saes,dora,incident,down
        env:
          gh_token: ${{ secrets.GH_PAT }}
      - uses: skaugvoll-actions/devlake-health-check@v1.0.1-beta
        with:
          url: http://google.com # should be good, so close issue
          repository: su-sisk/devlake-test-repo
          serviceName: saes
          labels: saes,dora,incident,down
        env:
          gh_token: ${{ secrets.GH_PAT }}
